import { RequestError } from "@octokit/request-error";
import { getInstallationOctokit, handleGithubError } from "./client";

export type UpdatedFile = {
  path: string;
  content: string;
  sha: string;
};

export type OpenDocPRParams = {
  owner: string;
  repo: string;
  prNumber: number;
  prTitle: string;
  updatedFiles: UpdatedFile[];
  installationId: number;
};

/**
 * Creates or updates a file on a specific branch.
 *
 * @param owner - The repository owner.
 * @param repo - The repository name.
 * @param path - The file path in the repository.
 * @param content - The new file content.
 * @param sha - The SHA of the existing file blob.
 * @param branch - The branch to update.
 * @param installationId - The GitHub App installation ID.
 */
async function updateFileOnBranch(
  owner: string,
  repo: string,
  path: string,
  content: string,
  sha: string,
  branch: string,
  installationId: number
): Promise<void> {
  const octokit = await getInstallationOctokit(installationId);
  const context = `updating ${owner}/${repo}/${path} on branch ${branch}`;

  try {
    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo,
      path,
      message: `docs: update ${path}`,
      content: Buffer.from(content, "utf-8").toString("base64"),
      sha,
      branch,
    });
  } catch (error) {
    handleGithubError(error, context);
  }
}

/**
 * Creates a new branch from the default branch HEAD.
 *
 * @param owner - The repository owner.
 * @param repo - The repository name.
 * @param baseBranch - The default branch name.
 * @param baseSha - The SHA of the default branch HEAD.
 * @param prNumber - The PR number used in the branch name.
 * @param installationId - The GitHub App installation ID.
 * @returns A Promise resolving to the created branch name.
 */
async function createBranch(
  owner: string,
  repo: string,
  baseBranch: string,
  baseSha: string,
  prNumber: number,
  installationId: number
): Promise<string> {
  const octokit = await getInstallationOctokit(installationId);

  let branchName = `docdrift/update-${prNumber}`;
  let attempts = 0;

  while (attempts <= 1) {
    const context = `creating branch ${branchName} for ${owner}/${repo}#${prNumber}`;

    try {
      await octokit.rest.git.createRef({
        owner,
        repo,
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      });

      return branchName;
    } catch (error) {
      if (
        error instanceof RequestError &&
        error.status === 409 &&
        attempts === 0
      ) {
        branchName = `docdrift/update-${prNumber}-${Date.now()}`;
        attempts++;
        continue;
      }

      handleGithubError(error, context);
    }
  }

  // This line is unreachable because the loop above always returns or throws.
  throw new Error(
    `Failed to create branch for ${owner}/${repo}#${prNumber} after retry`
  );
}

/**
 * Opens a documentation update pull request for the given original PR.
 *
 * @param params - The parameters for opening the documentation PR.
 * @returns A Promise resolving to the URL of the opened PR.
 */
export async function openDocPR(params: OpenDocPRParams): Promise<string> {
  const { owner, repo, prNumber, prTitle, updatedFiles, installationId } =
    params;
  const octokit = await getInstallationOctokit(installationId);

  let repositoryResponse;
  try {
    repositoryResponse = await octokit.rest.repos.get({
      owner,
      repo,
    });
  } catch (error) {
    handleGithubError(error, `fetching repository ${owner}/${repo}`);
  }

  const defaultBranch = repositoryResponse.data.default_branch;

  let refResponse;
  try {
    refResponse = await octokit.rest.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });
  } catch (error) {
    handleGithubError(
      error,
      `fetching default branch ref for ${owner}/${repo}`
    );
  }

  const baseSha = refResponse.data.object.sha;
  const branchName = await createBranch(
    owner,
    repo,
    defaultBranch,
    baseSha,
    prNumber,
    installationId
  );

  await Promise.all(
    updatedFiles.map((file) =>
      updateFileOnBranch(
        owner,
        repo,
        file.path,
        file.content,
        file.sha,
        branchName,
        installationId
      )
    )
  );

  let prResponse;
  try {
    prResponse = await octokit.rest.pulls.create({
      owner,
      repo,
      title: `docs: update documentation for PR #${prNumber}`,
      head: branchName,
      base: defaultBranch,
      body: `This PR was automatically generated by DocDrift.\n\nTriggered by: #${prNumber} ${prTitle}\n\nPlease review the changes and merge if they look correct.`,
    });
  } catch (error) {
    handleGithubError(error, `creating PR for ${owner}/${repo}#${prNumber}`);
  }

  return prResponse.data.html_url;
}
